on:
  schedule:
    - cron:  '0 0 * * 1'
name: update emojis list

jobs:
  update-gitmoji:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: clone carloscuesta/gitmoji
        run: gh repo clone carloscuesta/gitmoji

      - name: move ressource
        run: cp --verbose ./gitmoji/packages/gitmojis/src/gitmojis.json .

      - name: delete local carloscuesta/gitmoji
        run: rm --force --recursive gitmoji

      - name: check diff
        run: |
          if ! git diff --exit-code gitmojis.json; then
            echo "diff=true" >> $GITHUB_ENV
          fi

      - name: create branch and commit
        if: ${{ env.diff == 'true' }}
        run: |
          git checkout -b dependencie_$(date +%d-%m-%Y_%H-%M)
          git add gitmojis.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit --message '✨ gitmojis.json: update emojis list'

      - name: publish branch
        if: ${{ env.diff == 'true' }}
        run: git push -u origin HEAD

      - name: create pr
        if: ${{ env.diff == 'true' }}
        run: gh pr create --assignee alanJaouen --reviewer alanJaouen --fill
